config/routes.rb
GetCredible::Application.routes.draw do

  # resque
  mount Resque::Server.new, at: "/resque"

  # devise
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    invitations: 'users/invitations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    delete "users/omniauth_callbacks/disconnect/:provider",
       to: "users/omniauth_callbacks#disconnect",
       as: "disconnect_provider"
    get '/i' => 'users/invitations#edit', as: :accept_invitation
  end


  # root
  root to: 'home#index'

  # fixed
  get '/privacy' => 'home#privacy'
  get '/terms' => 'home#terms'
  get '/tour' => 'home#tour'
  get '/press' => 'home#press'
  get '/team' => 'home#team'
  get '/about' => 'home#about'
  get '/invite' => 'invite#index'
  get '/invite/state' => 'invite#state'
  get '/sitemap.:format' => 'home#sitemap', as: :sitemap
  post '/tags/search'
  match '/search' => 'users#index', as: 'search'

  # resources
  resources :activities, only: [:show]
  resources :invitation_messages, only: [:create]

  # user namespace
  match '/:user_id' => 'users#show', as: 'user'
  match '/:user_id/followers' => 'users#followers', as: 'user_followers'
  match '/:user_id/following' => 'users#following', as: 'user_following'
  scope "/:user_id", as: :user do
    resources :links, only: [:create, :index, :destroy]
    resources :endorsements
    resources :friendships
    resources :user_tags, only: [:index, :show, :create, :destroy], path: :tags do
      member do
        post :vote
        post :unvote
      end
    end
  end
end

app/views/shared/_endless_pagination.js.erb
<% if collection.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(collection) %>');
<% else %>
  $('.pagination').remove();
<% end %>
$('.pagination').hide();

app/views/shared/_explain.html.haml
.wrapper
  .featured
    -#%ul#slider.unstyled{:style => "height:200px"}
    %ul#explain.unstyled.slim
      %li
        = image_tag 'screen1.jpg'
        %h3 Ask your network
        %p Friends and colleagues can tag you with skills and traits to build your profile and personal brand.
      %li
        = image_tag 'screen2.jpg'
        %h3 Tell your story
        %p Endorsements let your connections go deeper by explaining why they tagged or vouched for you.
      %li
        = image_tag 'screen3.jpg'
        %h3 Get hired
        %p Give recruiters, hiring managers and clients an overview of your skills and personality by sharing your profile.
  / #video
  /   %h2 Watch our video and find out more
  /   - unless Rails.env.test? # stop warnings when running specs
  /     %iframe{ width: "560", height: "315", src: "http://www.youtube.com/embed/1yGSIHcAPqs", frameborder: "0", allowfullscreen: ''}
  /   %p
  /     %strong 98 seconds,
  /     and you're an expert!
  /     We have an 
  /     = link_to "illustrated tour", tour_path
  /     as well.

app/views/shared/_footer.html.haml
.wrapper#js_footer
  %footer
    .right
      %a{:href => "https://mixpanel.com/f/partner"}
        %img{:alt => "Mobile and Web Analytics", :src => "https://mixpanel.com/site_media/images/partner/badge_light.png"}/
      = link_to image_tag("icons/twitter.png"), "https://twitter.com/givebrand/"
      = link_to image_tag("icons/facebook.png"), "https://www.facebook.com/GiveBrand"
      = link_to image_tag("icons/googleplus.png"), "https://plus.google.com/116456795777845351010/posts"
      /= link_to image_tag("icons/linkedin.png"), "#"
      = link_to image_tag("icons/tumblr.png"), "http://blog.givebrand.com/"

    = link_to 'Tour', tour_path
    &bull;
    = link_to 'About', about_path
    &bull;
    = link_to 'Team', team_path
    &bull;
    = link_to 'Privacy policy', privacy_path
    &bull;
    = link_to 'Terms of use', terms_path
    -#&bull;
    -#= link_to 'Press', press_path
    &bull;
    = mail_to 'feedback@givebrand.com', 'Send feedback'
    %br
    %span Copyright &copy; GiveBrand 2012
    %br
    %br

= link_to '#', id: 'scroll_to_top', style: 'display: inline'  do
  %span Go to top

app/views/shared/_friend_nav.html.haml
- links_count = user.links.length
- following_count = user.followings.active.count
- followers_count = user.followers.active.count

%nav#friend-nav
  %ul#js-friendship-counts
    %li
      = link_to user_links_path(user) do
        %span= links_count
        = "Shared link".pluralize(links_count)
    %li#js-following-count
      = link_to user_following_path(user) do
        %span= following_count
        Following
    %li#js-followers-count
      = link_to user_followers_path(user) do
        %span= followers_count
        = "Followers".pluralize(followers_count)

app/views/shared/_friendship_button.html.haml
- if user_signed_in? && current_user != user
  - is_following = current_user.following?(user)
  %button{class: "js-friendship-action btn primary friendship #{is_following ? 'following' : 'follow'}",
  :'data-following' => is_following.to_s,
  :'data-follow-path' => user_friendships_path(user.username),
  :'data-unfollow-path' => user_friendship_path(user, :current),
  :'data-own-profile' => own_profile.to_s}
    %span= is_following ? 'Following' : 'Follow'

app/views/shared/_google_analytics.html.haml
- if Rails.env.production?
  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-1982765-4']);
    _gaq.push(['_setDomainName', 'givebrand.com']);
    _gaq.push(['_setAllowLinker', true]);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

app/views/shared/_header.html.haml
%header#global-header.app
  .wrapper
    %nav
      %ul#global-nav
        %li#gn-logo
          = link_to (user_signed_in? ? activity_path('all') : root_path), :class => 'logo' do
            %span give
            brand
        %li#global-search
          = form_tag search_path, :id => 'g-search', :method => :get do
            //= label_tag :q, "Search"
            = text_field_tag :q, '', :id => 'g-searchtext', :placeholder => 'Search people or tag'
            %button go

        - if user_signed_in?
          %li#gn-share.right
            = link_to 'Share', '#', id: 'js_share_btn', :class => "contrast"
          %li#gn-activity

            = link_to activity_path('all'), :class => (params[:controller] == 'activities' ? 'active' : nil) do
              //%span#gn-activity-counter 144
              Activity
          %li#gn-invite
            = link_to 'Invite', invite_path, :class => (params[:controller] == 'invite' ? 'active' : nil)

          %li#gn-profile
            = link_to user_path(current_user), :class => ((params[:controller] == 'users' && ['show', 'followers', 'following'].include?(params[:action]) && current_user == @user) ? 'active' : nil) do
              = image_tag current_user.avatar_url(:tiny)
              = current_user.name
            %ul
              %li= link_to "Edit Profile", edit_user_registration_path
              %li= link_to "Logout", destroy_user_session_path


        - else
          - unless Rails.env.test? # stop warnings when running specs
            = content_for :javascripts do
              %script{:src => "http://www.youtube.com/player_api", :type => "text/javascript"}

          %li
            = link_to 'What is GiveBrand?', '#', :class => 'video'
          %li
            = link_to 'Tour', tour_path, :class => (params[:controller] == 'home' && params[:action] == 'tour' ? 'active' : nil)
          %li
            = link_to 'About', about_path, :class => (params[:controller] == 'home' && params[:action] == 'about' ? 'active' : nil)

app/views/shared/_mixpanel.html.erb
<% if ENV['MIXPANEL_TOKEN'] %>
    <!-- start Mixpanel -->
    <script type="text/javascript">
        (function(d,c){var a,b,g,e;a=d.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===d.location.protocol?"https:":"http:")+'//api.mixpanel.com/site_media/js/api/mixpanel.2.js';b=d.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b);c._i=[];c.init=function(a,d,f){var b=c;"undefined"!==typeof f?b=c[f]=[]:f="mixpanel";g="disable track track_pageview track_links track_forms register register_once unregister identify name_tag set_config".split(" ");
        for(e=0;e<g.length;e++)(function(a){b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,0)))}})(g[e]);c._i.push([a,d,f])};window.mixpanel=c})(document,[]);
    mixpanel.init("<%=ENV['MIXPANEL_TOKEN']%>");
    </script>
    <!-- end Mixpanel -->
<% else %>
  <script type="text/javascript">
    var mixpanel = {
      track: function(msg){
        <% if Rails.env.development? %>
          if(console && typeof(console.log === 'function')){
            console.log("Track: " + msg);
          }
        <% end %>
      }
    };
  </script>
<% end %>

app/views/shared/_profile.html.haml
%section#profile.edit-area.vcard
  .details
    .left
      .photo
        = link_to image_tag(@user.avatar_url(:thumb)), user_path(@user), :id => "user_avatar_main"
        - if user_signed_in? && @user == current_user && show_guide?(current_user, params[:show_guide])
          = link_to image_tag("indicator.png"), nil, id: 'show_guide'
        %p.follow
          = render 'shared/friendship_button', user: @user, own_profile: current_user == @user
      = link_to user_path(@user), :class => 'no_underline' do
        %h1.fn= @user.name
      %h2.title= auto_link(@user.short_bio, :html => {:target => '_blank'}, :link => :urls)

    %ul.right
      - if @user.location.present?
        %li.location.adr
          %span.icon
          %span.locality= @user.location

      - if @user.personal_url.present?
        %li.web
          %span.icon
          = link_to 'Website', @user.personal_url, :target => '_blank', class: 'url'

      - if @user.twitter_handle.present?
        %li.twitter
          %span.icon
          = link_to 'Twitter', "https://twitter.com/#{@user.twitter_handle}", :target => '_blank', class: 'url'

app/views/shared/_sidebar_nav.html.haml
%nav#profile-nav
  .photo
    = link_to image_tag(current_user.avatar_url(:avatar)), edit_user_registration_path, :id => 'user_avatar_sidebar'

  .my-actions
    %h3
      = "Welcome #{link_to(current_user.short_name, edit_user_registration_path)}".html_safe

/= render 'shared/trending_tags'

app/views/shared/_sign_up.html.haml
- resource.change_error_message(:username, "This username is already registered. Want to #{link_to('login',new_session_path(resource_name))} or #{link_to('recover your password',new_password_path(resource_name))}?")
- resource.change_error_message(:email, "This email is already registered. Want to #{link_to('login',new_session_path(resource_name))} or #{link_to('recover your password',new_password_path(resource_name))}?")
%section.devise.sign_up
  %header#page-header
    %h1 Sign Up

  = simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :namespace => 'sign_up', :html => {:id => 'user_sign_up'}) do |f|
    %ul.inputs-list.bg
      %li= f.input :username, :required => false, :autofocus => true, :placeholder => "Username"
      %li= f.input :email, :placeholder => "Email"
      %li= f.input :password, :placeholder => "Password"
      %li.buttons_left= f.button :submit, "Sign up", class: 'btn large primary'
    %br

app/views/shared/_tags.html.haml
%ul.link_tags
  - tags.each do |tag|
    %li
      = link_to tag.name, search_path(q: tag.name)

app/views/shared/_trending_tags.html.haml
%nav.popular-tags
  %h3
    Trending Tags
    .view-all= link_to "View More", "#"
  %ul.horizontal
    %li
      = link_to "#" do
        Design
        %span +
    %li
      = link_to "#" do
        Interaction
        %span +
    %li
      = link_to "#" do
        CSS3
        %span +
    %li
      = link_to "#" do
        Experience
        %span +
    %li
      = link_to "#" do
        Responsive
        %span +
    %li
      = link_to "#" do
        HTML5
        %span +

app/views/shared/_twitter_social_network_script.html.haml
/ Twitter
:javascript
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");