config/routes.rb
GetCredible::Application.routes.draw do

  # resque
  mount Resque::Server.new, at: "/resque"

  # devise
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    invitations: 'users/invitations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    delete "users/omniauth_callbacks/disconnect/:provider",
       to: "users/omniauth_callbacks#disconnect",
       as: "disconnect_provider"
    get '/i' => 'users/invitations#edit', as: :accept_invitation
  end


  # root
  root to: 'home#index'

  # fixed
  get '/privacy' => 'home#privacy'
  get '/terms' => 'home#terms'
  get '/tour' => 'home#tour'
  get '/press' => 'home#press'
  get '/team' => 'home#team'
  get '/about' => 'home#about'
  get '/invite' => 'invite#index'
  get '/invite/state' => 'invite#state'
  get '/sitemap.:format' => 'home#sitemap', as: :sitemap
  post '/tags/search'
  match '/search' => 'users#index', as: 'search'

  # resources
  resources :activities, only: [:show]
  resources :invitation_messages, only: [:create]

  # user namespace
  match '/:user_id' => 'users#show', as: 'user'
  match '/:user_id/followers' => 'users#followers', as: 'user_followers'
  match '/:user_id/following' => 'users#following', as: 'user_following'
  scope "/:user_id", as: :user do
    resources :links, only: [:create, :index, :destroy]
    resources :endorsements
    resources :friendships
    resources :user_tags, only: [:index, :show, :create, :destroy], path: :tags do
      member do
        post :vote
        post :unvote
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include PreloaderHelper

  def index
    if user_signed_in?
      redirect_to activity_path('all')
    else
      @activity_items = ActivityItem.active.ordered.
        paginate page: params[:page], per_page: 10
      preload_activity_items(@activity_items)

      render 'index', layout: (request.xhr? ? false : true)
    end
  end

  def privacy
  end

  def terms
  end

  def tour
  end

  def press
  end

  def team
  end

  def about
  end

  def sitemap
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
- title("About - Givebrand")

.inner-page

  %h1 About GiveBrand

  %h2 What the heck is GiveBrand?

  %p It's harder than ever to stand out from the crowd these days.

  %p You spend hours updating your online profiles, trying to fill them with impressive credentials that will make people want to hire you. But a list of companies you've worked for doesn't really tell your story.

  %p Case in point: Ever been passed over for the perfect job by someone with nothing more than the perfect résumé? You know it should be about more than that.

  %p Time to cut through the B.S. and show off who you really are — your skills and personality — not just your jobs.



  %h2 GiveBrand is powered by people.

  %p Go straight to the people who know you best — your friends and colleagues — and ask them tag you.

  %p When real people can vouch for your skills, you gain credibility.

  %p With GiveBrand, there are no meaningless scores, no declarations of "influence"…you get a streamlined profile with a cloud full of words and phrases that shape your brand and help tell your story. Share it with recruiters, HR managers, potential clients — anyone you want.

  %p It's never been about us…we're just the vehicle to move you from where you are now to where you want to be.

app/views/home/index.html.haml
#content-wrap
  %header#page-header
    %h1 Latest Activity

  #content
    %section.content
      .feed
        %ul.list-view.unstyled#js_collection_list
          = render 'activities/activities'

      = will_paginate @activity_items

%aside
  = render 'shared/sign'

app/views/home/index.js.erb
$('#js_collection_list').append('<%= j render('activities/activities') %>');
<%= render 'shared/endless_pagination', collection: @activity_items %>

app/views/home/press.html.haml
- title("Press - Givebrand")

.inner-page

  %h1 Press

app/views/home/privacy.html.haml
- title("Privacy Policy - Givebrand")

.inner-page

  %h1 Privacy Policy

  %p When accessing our Website, Give Brand will learn certain information about you during your visit. How we will handle information we learn about you depends upon what you do when visiting our site.

  %p If you visit our site to read or download information on our pages, we collect and store only the following information about you:

  %ol
    %li The name of the domain from which you access the Internet.
    %li The date and time you access our site.
    %li The Internet address of the website you used to link directly to our site.
    %li Your name.
    %li Your email.
    %li Your location.
    %li Your title.
    %li Your website.
    %li Your picture.
    %li Your 3rd party service accounts.
    %li Your skills.
    %li Your abilities.
    %li Your tags.
    %li Your contacts.
    %li Your preferences

  %p If you identify yourself by sending us an e-mail containing personal information, then the information collected will be solely used to respond to your message.

  %p The information collected is for statistical purposes. Give Brand may use software programs to create summary statistics, which are used for such purposes as assessing the number of visitors to the different sections of our site, what information is of most and least interest, determining technical design specifications, and identifying system performance or problem areas.

  %p For site security purposes and to ensure that this service remains available to all users, Give Brand uses software programs to monitor network traffic to identify unauthorized attempts to upload or change information, or otherwise cause damage.

  %p Give Brand will not obtain personally-identifying information about you when you visit our site, unless you choose to provide such information to us, nor will such information be sold or otherwise transferred to unaffiliated third parties without the approval of the user at the time of collection.

app/views/home/team.html.haml
- title("Team - Givebrand")

.inner-page
  %h1.border The people behind GiveBrand

  %ul.team-list
    %li
      = link_to image_tag("team/russ.jpg"), "http://givebrand.com/russ"
      %h2
        = link_to "Russ Trpkovski", "http://givebrand.com/russ"
        %span Co-Founder
      %p
        Russ is a Michigan native who, like 90 percent of other Michiganders his age, now lives in Chicago. He has a technical consulting background — by day, he makes a lot of complicated PowerPoints — and follows the financial markets, reads nonfiction, and drinks craft beers in his spare time. When he isn't shaping GiveBrand with the rest of the design and developer team.
        %br
        %a{:href => 'http://twitter.com/hriste', :target => '_blank', :class => "twitter-url btn primary small light"} @hriste

    %li
      = link_to image_tag("team/bobi.jpg"), "http://givebrand.com/bobanj"
      %h2
        = link_to "Boban Jovanoski", "http://givebrand.com/bobanj"
        %span Co-Founder
      %p
        Boban is a team player, new-tech enthusiast, programming language explorer and all-around geek (tag him on it). He cofounded MKRUG, the Macedonian Ruby Users Group. He lives in Hamburg, Germany, and works at
        %a{:href => 'http://www.qype.co.uk/', :target => '_blank'} Qype
        , Europe's largest user-generated review site. In what little free time he has, Boban rides his bike and ponders world domination.
        %br
        %a{:href => 'http://twitter.com/BobiRuby', :target => '_blank', :class => "twitter-url btn primary small light"} @BobiRuby

    %li
      = link_to image_tag("team/dalibor.jpg"), "http://givebrand.com/dalibor"
      %h2
        = link_to "Dalibor Nasevic", "http://givebrand.com/dalibor"
        %span Co-Founder
      %p
        Software Professional with passion for building successful web products & teams with strong desire to win. Dalibor is an award-winning Android mobile application developer and open-source contributor working on numerous Ruby on Rails projects since 2007. He is co-founder and organizer of MKRUG — the Macedonian Ruby users group, and works at
        %a{:href => 'http://www.siyelo.com/', :target => '_blank'} Siyelo
        — Ruby on Rails consultancy from Cape Town.
        %br
        %a{:href => 'http://twitter.com/dnasevic', :target => '_blank', :class => "twitter-url btn primary small light"} @dnasevic

    %li
      = link_to image_tag("team/paige.jpg"), "http://givebrand.com/paigeworthy"
      %h2
        = link_to "Paige Worthy", "http://givebrand.com/paigeworthy"
        %span Content Manager
      %p
        Midwest born and bred — with a short stint in New York City for good measure — Paige is a full-time content strategist lending spunk, sass and voice to small businesses and startups by the hour. She wrote GiveBrand's site copy and all other e-mail and marketing collateral. (Feedback welcome!) She loves snarky blogs, cat videos, food and riding bikes.
        %br
        %a{:href => 'http://twitter.com/paigeworthy', :target => '_blank', :class => "twitter-url btn primary small light"} @paigeworthy

app/views/home/tour.html.haml
- title("Tour - Givebrand")

%div.tour_item.first
  %h2#n1
    %span.number 1
    Create your profile
  = image_tag"tour-screen-1.jpg"
  %p GiveBrand is the simple, streamlined way to showcase your personal brand. Make your profile more inviting by adding your contact information, a photo and a short description of yourself.
  //%p= link_to "Sign up now for free", new_registration_path(:user), :class => 'btn primary large light'
%div.tour_item
  %h2#n2
    %span.number 2
    Invite your contacts
  = image_tag"tour-screen-2.jpg"
  %p Get started: Add contacts one by one, by e-mail, or link your Twitter account to GiveBrand and find friends that way. We'll invite them to join the site and let you know if they've accepted. (You can also link to your profile on any social media site!)
  //%p= link_to "Sign up now for free", new_registration_path(:user), :class => 'btn primary large light'
%div.tour_item
  %h2#n3
    %span.number 3
    Tag and be tagged
  = image_tag"tour-screen-3.jpg"
  %p Assign tags to your contacts or, if you see one there you agree with, vouch a tag they've already been given. Encourage them to return the favor - the more you give, the more you get!
  //%p= link_to "Sign up now for free", new_registration_path(:user), :class => 'btn primary large light'
%div.tour_item
  %h2#n4
    %span.number 4
    Add more details
  = image_tag"tour-screen-4.jpg"
  %p If a single word or phrase isn't enough for a tag to speak for itself, add a short, Twitter-style endorsement to explain a tag you've given them. Anyone who visits their profile will be able to see it.
  //%p= link_to "Sign up now for free", new_registration_path(:user), :class => 'btn primary large light'
%div.tour_item
  %h2#n5
    %span.number 5
    Keep tabs on your brand
  = image_tag"tour-screen-5.jpg"
  %p Hover over a word in your tag cloud to see how you stack up against other GiveBrand users with the same tag. The more you're tagged and vouched for in a certain category, the higher your credibility.
  //%p= link_to "Sign up now for free", new_registration_path(:user), :class => 'btn primary large light'