config/routes.rb
GetCredible::Application.routes.draw do

  # resque
  mount Resque::Server.new, at: "/resque"

  # devise
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    invitations: 'users/invitations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    delete "users/omniauth_callbacks/disconnect/:provider",
       to: "users/omniauth_callbacks#disconnect",
       as: "disconnect_provider"
    get '/i' => 'users/invitations#edit', as: :accept_invitation
  end


  # root
  root to: 'home#index'

  # fixed
  get '/privacy' => 'home#privacy'
  get '/terms' => 'home#terms'
  get '/tour' => 'home#tour'
  get '/press' => 'home#press'
  get '/team' => 'home#team'
  get '/about' => 'home#about'
  get '/invite' => 'invite#index'
  get '/invite/state' => 'invite#state'
  get '/sitemap.:format' => 'home#sitemap', as: :sitemap
  post '/tags/search'
  match '/search' => 'users#index', as: 'search'

  # resources
  resources :activities, only: [:show]
  resources :invitation_messages, only: [:create]

  # user namespace
  match '/:user_id' => 'users#show', as: 'user'
  match '/:user_id/followers' => 'users#followers', as: 'user_followers'
  match '/:user_id/following' => 'users#following', as: 'user_following'
  scope "/:user_id", as: :user do
    resources :links, only: [:create, :index, :destroy]
    resources :endorsements
    resources :friendships
    resources :user_tags, only: [:index, :show, :create, :destroy], path: :tags do
      member do
        post :vote
        post :unvote
      end
    end
  end
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  # Accessible
  # we need both tag and user to create a user_tag so it can be endorsed
  # tag_name is the name of the new tag if there isn't one
  # user_id is the user who is endorsed
  attr_accessible :description, :endorsed_by_id, :user_tag_id, :endorser

  # Associations
  belongs_to :user_tag
  belongs_to :endorser, :class_name => 'User', :foreign_key => :endorsed_by_id
  has_one :tag, :through => :user_tag
  has_one :user, :through => :user_tag
  has_many :activity_items, :as => :item, :dependent => :destroy

  # Validations
  validates :endorser, presence: true, :allow_nil => false
  validates :user_tag_id, presence: true, :allow_nil => false
  validates :description, presence: true
  validates :description, :length => {:minimum => 10, :maximum => 300}
  validate :user_can_not_endorse_himself

  # Callbacks
  before_save :create_vote

  #Scopes
  scope :latest, order("created_at desc")

  private
  def user_can_not_endorse_himself
    if user_tag && user_tag.user_id == endorsed_by_id
      errors.add(:description, "You can't endorse yourself")
    end
  end

  def create_vote
    endorser.add_vote(user_tag, false) unless endorser.voted_for?(user_tag)
  end

end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_user

  def edit
    @endorsement = current_user.outgoing_endorsements.find(params[:id])
  end

  def create
    @endorsement = current_user.outgoing_endorsements.new(params[:endorsement])

    if @endorsement.save
      ActivityItem.create(user: current_user, item: @endorsement,
                          target: @user, tags: [@endorsement.tag])
      UserMailer.endorse_email(@endorsement).deliver
      render :create_success
    else
      render :create_failure
    end
  end

  def update
    @endorsement = current_user.outgoing_endorsements.find(params[:id])

    if @endorsement.update_attributes(params[:endorsement])
      render :update_success
    else
      render :update_failure
    end
  end

  def destroy
    @endorsement = current_user.incoming_endorsements.find(params[:id])
    @endorsement.destroy
  end

  private
  def load_user
    @user = User.find_by_username!(params[:user_id])
  end

end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/views/endorsements/_endorsement.html.haml
%li{id: dom_id(endorsement)}
  .js_endorsement
    = auto_link(endorsement.description, :html => {:target => '_blank'}, :link => :urls)
    %span.endorser
      Written by
      = link_to endorsement.endorser.short_name, user_path(endorsement.endorser)
      %span ,
      = time_ago_in_words(endorsement.created_at)
      %span ago
    - if user_signed_in? && current_user == @user
      = link_to "X", user_endorsement_path(endorsement.endorser, endorsement), remote: true, method: :delete, data: { confirm: 'Are you sure you want to delete this endorsement?' }, class: 'js-endorsement-delete endorse-delete'
    - if user_signed_in? && current_user == endorsement.endorser
      = link_to "edit", edit_user_endorsement_path(endorsement.endorser, endorsement), remote: true, class: 'js-endorsement-edit endorse-edit'

app/views/endorsements/_endorsements.html.haml
%section#endorsements{class: @user.user_tags.present? ? nil : 'hide'}
  %hr.divider.strong
  #tag-listing.listing-wrap
    #page-header.gray
      %h1 Endorsements
      -#- if user_signed_in? && @user != current_user
      -#  = link_to "Write an endorsement", "#", id: 'write_endorsement_button', class: "right btn primary small"

    = render 'endorsements/write_endorsement_form', hide: !(user_signed_in? && current_user != @user), endorsement: Endorsement.new
    .listing
      %ul#endorsements_list
        - @user_tag_endorsements.each do |user_tag, endorsements|
          = render 'endorsements/user_tag_endorsements', user_tag: user_tag, endorsements: endorsements

    #endorsements_form_keeper.hide
      =render 'endorsements/form', endorsement: Endorsement.new

app/views/endorsements/_form.html.haml
= simple_form_for([@user, endorsement], remote: true, html: {id: 'js-endorsement-form', class: "#{endorsement.new_record? ? '' : 'js-endorsement-form-edit'} tag-endorse-text" }) do |f|
  - if endorsement.new_record?
    %p Write your endorsement here:
  - else
    %p Edit your endorsement:
  = f.input :user_tag_id, as: :hidden
  = f.input :description, label: false, input_html: {rows: 2}
  %span.hint
    %span#endorsement_word_counter 300
    characters remaining
  .buttons
    = f.button :submit, (endorsement.new_record? ? "Endorse" : "Save"), class: 'btn primary'
    %span.inline
      = link_to 'Cancel', '#', class: 'js-cancel-endorsement'
    %span.loader.inline.hide
      = image_tag 'ajax_loader.gif'

app/views/endorsements/_user_tag_endorsements.html.haml
%li.endorsement_li{id: "endorse_#{user_tag.id}_container"}
  %span.score{id:"endorse_#{user_tag.id}_score", class: (endorsements.length == 0 ? "hide" : nil)}= endorsements.length
  %span.name= user_tag.tag.name
  %span.endorse
    - if user_signed_in? && @user != current_user
      = link_to "Endorse this tag", "#",id: "endorse_#{user_tag.id}_link", class: 'js-endorse-tag action', :'data-user_tag_id' => user_tag.id
    = link_to "Minimize", "#", :class => "js-endorsements-toggle", :'data-user_tag_id' => user_tag.id
    = link_to "Expand", "#", :class => "js-endorsements-toggle hide", :'data-user_tag_id' => user_tag.id
  %ul.tag-endorse{id: "endorsements_#{user_tag.id}_list"}
    = render :partial => 'endorsements/endorsement', :collection => endorsements

app/views/endorsements/_write_endorsement_form.html.haml
= simple_form_for([@user, endorsement], remote: true, html: {id: 'write_endorsement_form', class:"add-endorsement #{hide ? 'hide' : '' }" }) do |f|
  = f.input :user_tag_id, as: :select, collection: load_user_tags(@user), label: false, input_html:{id: 'write_endorsement_user_tag_id', :'data-placeholder' => "Choose a tag"}
  = f.input :description, label: false, input_html:{id: 'write_endorsement_description', placeholder: "If one word or phrase isn't enough, offer a little insight into why you tagged this profile the way you did", rows: 2}
  = hidden_field_tag :write_endorsement, true
  %span.hint.right
    %span.loader.inline.hide
      = image_tag 'ajax_loader.gif'
    %span#write_endorsement_word_counter 300
    .buttons
      = f.button :submit, "Endorse", class: 'btn small'
      -#%span.inline
      -#  = link_to 'Cancel', '#', id: 'write_endorsement_cancel', class: 'cancel'

app/views/endorsements/create.js.erb
$(".js-endorsement-form .loader").addClass('hide');
<% unless @endorsement.errors.present? %>
$("#endorsements_<%=@endorsement.user_tag_id%>_list").prepend('<%=escape_javascript(render :partial => 'endorsements/endorsement', :locals => {:endorsement => @endorsement}) %>');
$('.js-endorsement-form #endorsement_description').val('');
$('.js-endorsement-form #endorsement_user_tag_id').val('');
$('.js-endorsement-form #user_tag_id').val('');
$(".js-endorsement-form").hide();
if($("#endorsements_<%=@endorsement.user_tag_id%>_list").children().length == 1){
  $("#endorse_<%=@endorsement.user_tag_id%>_container .js-endorsements-toggle").removeClass('hide').click();
} else {
  if ($("#endorsements_<%=@endorsement.user_tag_id%>_list").hasClass('hide')){
    $("#endorse_<%=@endorsement.user_tag_id%>_container .js-endorsements-toggle").text("Hide all endorsements");
    $("#endorsements_<%=@endorsement.user_tag_id%>_list").removeClass('hide').slideDown(800);
  } else{
    $("#endorse_<%=@endorsement.user_tag_id%>_container .js-endorsements-toggle").text("Show all endorsements");
    $("#endorsements_<%=@endorsement.user_tag_id%>_list").addClass('hide').slideUp(800);
  }
}
<% else %>
<% if @endorsement.errors[:description].blank? %>
  $.getCredible.displayNotification('error', 'The user does not own the tag you want to endorse');
<% end %>
$(".js-endorsement-form").replaceWith('<%=escape_javascript(render :partial => 'endorsements/form')%>');
<% end %>

app/views/endorsements/create_failure.js.erb
<% if params[:write_endorsement].present? %>
var writeEndorsementForm = $("#write_endorsement_form");
writeEndorsementForm.find(".loader").addClass('hide');
writeEndorsementForm.replaceWith('<%=j(render 'endorsements/write_endorsement_form', hide: false, endorsement: @endorsement)%>');
$("#write_endorsement_user_tag_id").chosen();
$("#write_endorsement_description").limit('300', $("#write_endorsement_word_counter"));
<% else %>
$("#js-endorsement-form").replaceWith('<%= j(render 'endorsements/form', endorsement: @endorsement)%>');
var endorsementTextarea = $("#js-endorsement-form").find("#endorsement_description");
endorsementTextarea.limit('300', $("#endorsement_word_counter"));
endorsementTextarea.focus();
<% end %>

app/views/endorsements/create_success.js.erb
<% if params[:write_endorsement].present? %>
$("#write_endorsement_form").replaceWith('<%=j(render 'write_endorsement_form', hide: false, endorsement: Endorsement.new)%>');
$("#write_endorsement_user_tag_id").chosen();
$("#write_endorsement_description").limit('300', $("#write_endorsement_word_counter"));
<% end %>
$("#js-no-endorsements").remove();
$("#js-endorsement-form").remove();

var userTagEndorsementContainer = $("#endorse_<%=@endorsement.user_tag_id-%>_container");
var userTagEndorsements = '<%=j(render 'user_tag_endorsements', user_tag: @endorsement.user_tag, endorsements: @endorsement.user_tag.endorsements.latest ) %>';
if(userTagEndorsementContainer.length){
  userTagEndorsementContainer.replaceWith(userTagEndorsements);
} else {
  $("#endorsements_list").prepend(userTagEndorsements);
}
$("#endorsements_form_keeper").html('<%= j(render 'endorsements/form', endorsement: Endorsement.new)%>');
mixpanel.track("Endorsement");

app/views/endorsements/destroy.js.erb
$("#<%=dom_id(@endorsement)%>").remove();
var endorseContainer = $('#endorse_<%= @endorsement.user_tag_id %>_container');
var numEndorsements = endorseContainer.find('span.score');
numEndorsements.html(parseInt(numEndorsements.text()) - 1);
var endorsementsList = $('#endorsements_<%= @endorsement.user_tag_id %>_list');
if (endorsementsList.length > 0 && endorsementsList.children().length == 0){
  endorseContainer.remove();
}

app/views/endorsements/edit.js.erb
//$('.js-endorsement-form-edit').each(function () {
//  var form = $(this);
//  var endorsement = form.parent('li').find('> .js_endorsement');
//  endorsement.show();
//  form.remove();
//});
var endorsement = $("#js-endorsement-form").parent('li').find('> .js_endorsement');
endorsement.show();
$("#js-endorsement-form").remove();
$("#endorsements_form_keeper").html('<%= j(render 'endorsements/form', endorsement: @endorsement)%>');
var currentEndorsement = $("#<%= dom_id @endorsement %>");
currentEndorsement.find(".js_endorsement").hide();
currentEndorsement.prepend($("#js-endorsement-form"));
var endorsementTextarea = $("#js-endorsement-form").find("#endorsement_description");
endorsementTextarea.limit('300', $("#endorsement_word_counter"));
endorsementTextarea.focus();

app/views/endorsements/update_failure.js.erb
var currentEndorsement = $("#<%= dom_id @endorsement %>");
currentEndorsement.find(".js_endorsement").hide();
currentEndorsement.find('form:first').remove();
currentEndorsement.append('<%= j(render 'endorsements/form', endorsement: @endorsement) %>');

app/views/endorsements/update_success.js.erb
var currentEndorsement = $("#<%= dom_id @endorsement %>");
currentEndorsement.replaceWith('<%= j(render 'endorsements/endorsement', endorsement: @endorsement) %>')
$("#endorsements_form_keeper").html('<%= j(render 'endorsements/form', endorsement: Endorsement.new)%>');