config/routes.rb
GetCredible::Application.routes.draw do

  # resque
  mount Resque::Server.new, at: "/resque"

  # devise
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    invitations: 'users/invitations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    delete "users/omniauth_callbacks/disconnect/:provider",
       to: "users/omniauth_callbacks#disconnect",
       as: "disconnect_provider"
    get '/i' => 'users/invitations#edit', as: :accept_invitation
  end


  # root
  root to: 'home#index'

  # fixed
  get '/privacy' => 'home#privacy'
  get '/terms' => 'home#terms'
  get '/tour' => 'home#tour'
  get '/press' => 'home#press'
  get '/team' => 'home#team'
  get '/about' => 'home#about'
  get '/invite' => 'invite#index'
  get '/invite/state' => 'invite#state'
  get '/sitemap.:format' => 'home#sitemap', as: :sitemap
  post '/tags/search'
  match '/search' => 'users#index', as: 'search'

  # resources
  resources :activities, only: [:show]
  resources :invitation_messages, only: [:create]

  # user namespace
  match '/:user_id' => 'users#show', as: 'user'
  match '/:user_id/followers' => 'users#followers', as: 'user_followers'
  match '/:user_id/following' => 'users#following', as: 'user_following'
  scope "/:user_id", as: :user do
    resources :links, only: [:create, :index, :destroy]
    resources :endorsements
    resources :friendships
    resources :user_tags, only: [:index, :show, :create, :destroy], path: :tags do
      member do
        post :vote
        post :unvote
      end
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  include PreloaderHelper

  before_filter :authenticate_user!

  def show
    @activity_items = load_activity_items
    preload_activity_items(@activity_items)

    render 'index', layout: (request.xhr? ? false : true)
  end

  private
    def load_activity_items
      case params[:id]
      when 'incoming'
        current_user.incoming_activities_for_others.paginate(paginate_options)
      when 'outgoing'
        current_user.outgoing_activities.paginate(paginate_options)
      when 'all'
        current_user.all_activities.paginate(paginate_options)
      else
        raise ActiveRecord::RecordNotFound
      end
    end

    def paginate_options
      { page: params[:page], per_page: 10 }
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def activity_tab_class(name)
    params[:id] == name ? 'active' : nil
  end

  def activity_item_class(activity_item)
    outgoing_activity?(activity_item) ? 'you' : nil
  end

  def activity_description(activity_item)
    if outgoing_activity?(activity_item)
      outgoing_activity_description(activity_item)
    else
      incoming_activity_description(activity_item)
    end
  end

  def apostrophe(term)
    term =~ /s$/i ? "'" : "'s"
  end

  def incoming_activity_description(activity_item)
    user = activity_item.user
    target = activity_item.target
    subject_link = subject_link(user)
    object_link = object_link(target)

    case activity_item.item_type
    when 'Vote'
      "Check YOU out! #{subject_link} vouched for you"
    when 'UserTag'
      if user == activity_item.target
        "Sweet! You tagged yourself"
      else
        "Sweet! #{subject_link} tagged #{object_link}"
      end
    when 'Endorsement'
      "Cool! #{subject_link} endorsed #{object_link}"
    when 'Link'
      "#{subject_link} shared a #{link_to('link', activity_item.item.url, target: '_blank')}"
    end.html_safe
  end

  def outgoing_activity_description(activity_item)
    user = activity_item.user
    target = activity_item.target
    subject_link = subject_link(user)
    object_link = object_link(target)

    case activity_item.item_type
    when 'Vote'
      "#{subject_link} vouched for #{object_link}"
    when 'UserTag'
      if user == activity_item.target
        "#{user_link(user)} tagged themself"
      else
        "#{subject_link} tagged #{object_link}"
      end
    when 'Endorsement'
      "#{subject_link} wrote an endorsement for #{object_link}"
    when 'Link'
      "#{subject_link} shared a #{link_to('link', activity_item.item.url, target: '_blank')}"
    end.html_safe
  end

  private
  def outgoing_activity?(activity_item)
    activity_item.target != current_user
  end

  def subject_link(user)
    current_user && current_user == user ? "You" : user_link(user)
  end

  def object_link(target)
    current_user && current_user == target ? "you" : user_link(target)
  end
end

app/views/activities/_activities.html.haml
- @activity_items.each do |activity_item|
  = render "activities/elements/#{activity_item.item_type.underscore}", activity_item: activity_item

app/views/activities/index.html.haml
#content-wrap
  %header#page-header
    %nav.right
      %ul.tabs
        %li.first{:class => activity_tab_class('all')}
          = link_to 'All', activity_path('all'), :class => 'js-remote'
        %li{:class => activity_tab_class('incoming')}
          = link_to 'Notifications', activity_path('incoming'), :class => 'js-remote'
        %li.last{:class => activity_tab_class('outgoing')}
          = link_to 'My Activity', activity_path('outgoing'), :class => 'js-remote'
    %h1 Recent Activity


  #content
    %section.content

      .feed
        %ul.list-view.unstyled#js_collection_list

          - if @activity_items.present?
            = render 'activities'
          - else
            .ngo
              %p
                %span No recent activity
                %br
                == #{link_to "Brand Yourself", user_path(current_user)} or #{link_to "invite people", new_user_invitation_path}.

      = will_paginate @activity_items

%aside

app/views/activities/index.js.erb
$('#js_collection_list').append('<%= j render('activities') %>');
<%= render 'shared/endless_pagination', collection: @activity_items %>

app/views/activities/show.html.haml
#content
  %section#activity
    %header#page-header
      %h1 Activity feed
      %nav
        %ul.tabs
          %li.first{:class => activity_active_class('all')}
            = link_to 'All', activity_path('all')
          %li{:class => activity_active_class('incoming')}
            = link_to 'Incoming activity', activity_path('incoming')
          %li.last{:class => activity_active_class('outgoing')}
            = link_to 'My activity', activity_path('outgoing')

    .feed
      %ul.list-view.unstyled
        - @activity_items.each do |activity_item|
          %li{:class => activity_class(activity_item)}
            .content
              .photo
                = link_to activity_item.user do
                  = image_tag activity_item.user.avatar.url(:small)
                  = image_tag activity_item.target.avatar.url(:tiny), :class => 'over'
              .icon
              %h2
                = activity_description(activity_item)
              %time= activity_item.created_at.strftime("%d. %b %Y")

    .pagination
      = will_paginate @activity_items


%aside
  = render :partial => 'shared/sidebar_nav', :locals => { :user => current_user }
  = render :partial => 'shared/sidebar_activity'